
# base
SET( BASE_COMMON_SRCS 
	src/common/appbase.cpp
	src/common/arcall.cpp
	src/common/arcfind.cpp
	src/common/archive.cpp
	src/common/clntdata.cpp
	src/common/cmdline.cpp
	src/common/config.cpp
	src/common/convauto.cpp
	src/common/datetime.cpp
	src/common/datstrm.cpp
	src/common/dircmn.cpp
	src/common/dummy.cpp
	src/common/dynarray.cpp
	src/common/dynlib.cpp
	src/common/dynload.cpp
	src/common/encconv.cpp
	src/common/event.cpp
	src/common/extended.c
	src/common/ffile.cpp
	src/common/file.cpp
	src/common/fileback.cpp
	src/common/fileconf.cpp
	src/common/filefn.cpp
	src/common/filename.cpp
	src/common/filesys.cpp
	src/common/filtall.cpp
	src/common/filtfind.cpp
	src/common/fmapbase.cpp
	src/common/fs_arc.cpp
	src/common/fs_filter.cpp
	src/common/fs_mem.cpp
	src/common/hash.cpp
	src/common/hashmap.cpp
	src/common/init.cpp
	src/common/intl.cpp
	src/common/ipcbase.cpp
	src/common/list.cpp
	src/common/log.cpp
	src/common/longlong.cpp
	src/common/memory.cpp
	src/common/mimecmn.cpp
	src/common/module.cpp
	src/common/msgout.cpp
	src/common/mstream.cpp
	src/common/object.cpp
	src/common/platinfo.cpp
	src/common/powercmn.cpp
	src/common/process.cpp
	src/common/regex.cpp
	src/common/sstream.cpp
	src/common/stdpbase.cpp
	src/common/stopwatch.cpp
	src/common/strconv.cpp
	src/common/stream.cpp
	src/common/string.cpp
	src/common/sysopt.cpp
	src/common/tarstrm.cpp
	src/common/textbuf.cpp
	src/common/textfile.cpp
	src/common/tokenzr.cpp
	src/common/txtstrm.cpp
	src/common/uri.cpp
	src/common/utilscmn.cpp
	src/common/variant.cpp
	src/common/wfstream.cpp
	src/common/wxchar.cpp
	src/common/xti.cpp
	src/common/xtistrm.cpp
	src/common/zipstrm.cpp
	src/common/zstream.cpp )
SOURCE_GROUP( "Common Sources" FILES ${BASE_COMMON_SRCS} )
SET( BASE_COMMON_HDRS 
	include/wx/afterstd.h
	include/wx/app.h
	include/wx/apptrait.h
	include/wx/archive.h
	include/wx/arrstr.h
	include/wx/beforestd.h
	include/wx/buffer.h
	include/wx/build.h
	include/wx/chkconf.h
	include/wx/clntdata.h
	include/wx/cmdline.h
	include/wx/confbase.h
	include/wx/config.h
	include/wx/containr.h
	include/wx/convauto.h
	include/wx/cpp.h
	include/wx/datetime.h
	include/wx/datstrm.h
	include/wx/dde.h
	include/wx/debug.h
	include/wx/defs.h
	include/wx/dir.h
	include/wx/dlimpexp.h
	include/wx/dynarray.h
	include/wx/dynlib.h
	include/wx/dynload.h
	include/wx/encconv.h
	include/wx/event.h
	include/wx/except.h
	include/wx/features.h
	include/wx/ffile.h
	include/wx/file.h
	include/wx/fileconf.h
	include/wx/filefn.h
	include/wx/filename.h
	include/wx/filesys.h
	include/wx/fontenc.h
	include/wx/fontmap.h
	include/wx/fs_arc.h
	include/wx/fs_filter.h
	include/wx/fs_mem.h
	include/wx/fs_zip.h
	include/wx/hash.h
	include/wx/hashmap.h
	include/wx/hashset.h
	include/wx/iconloc.h
	include/wx/init.h
	include/wx/intl.h
	include/wx/iosfwrap.h
	include/wx/ioswrap.h
	include/wx/ipc.h
	include/wx/ipcbase.h
	include/wx/isql.h
	include/wx/isqlext.h
	include/wx/link.h
	include/wx/list.h
	include/wx/log.h
	include/wx/longlong.h
	include/wx/math.h
	include/wx/memconf.h
	include/wx/memory.h
	include/wx/memtext.h
	include/wx/mimetype.h
	include/wx/module.h
	include/wx/msgout.h
	include/wx/mstream.h
	include/wx/object.h
	include/wx/platform.h
	include/wx/platinfo.h
	include/wx/power.h
	include/wx/process.h
	include/wx/ptr_scpd.h
	include/wx/recguard.h
	include/wx/regex.h
	include/wx/scopeguard.h
	include/wx/snglinst.h
	include/wx/sstream.h
	include/wx/stack.h
	include/wx/stackwalk.h
	include/wx/stdpaths.h
	include/wx/stockitem.h
	include/wx/stopwatch.h
	include/wx/strconv.h
	include/wx/stream.h
	include/wx/string.h
	include/wx/sysopt.h
	include/wx/tarstrm.h
	include/wx/textbuf.h
	include/wx/textfile.h
	include/wx/thread.h
	include/wx/timer.h
	include/wx/tokenzr.h
	include/wx/txtstrm.h
	include/wx/types.h
	include/wx/uri.h
	include/wx/utils.h
	include/wx/variant.h
	include/wx/vector.h
	include/wx/version.h
	include/wx/volume.h
	include/wx/wfstream.h
	include/wx/wx.h
	include/wx/wxchar.h
	include/wx/wxprec.h
	include/wx/xti.h
	include/wx/xtistrm.h
	include/wx/zipstrm.h
	include/wx/zstream.h )
SOURCE_GROUP( "Common Headers" FILES ${BASE_COMMON_HDRS} )
SET( BASE_HTML_HDRS
	include/wx/html/forcelnk.h )
SOURCE_GROUP( "wxHTML Headers" FILES ${BASE_HTML_HDRS} )

IF( WIN32 )
	SET( BASE_MSW_SRCS
		src/msw/basemsw.cpp
		src/msw/crashrpt.cpp
		src/msw/dde.cpp
		src/msw/debughlp.cpp
		src/msw/dir.cpp
		src/msw/dlmsw.cpp
		src/msw/main.cpp
		src/msw/mimetype.cpp
		src/msw/mslu.cpp
		src/msw/power.cpp
		src/msw/regconf.cpp
		src/msw/registry.cpp
		src/msw/snglinst.cpp
		src/msw/stackwalk.cpp
		src/msw/stdpaths.cpp
		src/msw/thread.cpp
		src/msw/utils.cpp
		src/msw/utilsexc.cpp
		src/msw/volume.cpp )
	SOURCE_GROUP( "MSW Sources" FILES ${BASE_MSW_SRCS} )
	SET( BASE_MSW_HDRS
		include/wx/msw/apptbase.h
		include/wx/msw/apptrait.h
		include/wx/msw/chkconf.h
		include/wx/msw/crashrpt.h
		include/wx/msw/dde.h
		include/wx/msw/debughlp.h
		include/wx/msw/gccpriv.h
		include/wx/msw/genrcdefs.h
		include/wx/msw/libraries.h
		include/wx/msw/mimetype.h
		include/wx/msw/mslu.h
		include/wx/msw/private.h
		include/wx/msw/regconf.h
		include/wx/msw/registry.h
		include/wx/msw/seh.h
		include/wx/msw/stackwalk.h
		include/wx/msw/stdpaths.h
		include/wx/msw/winundef.h
		include/wx/msw/wrapcctl.h
		include/wx/msw/wrapcdlg.h
		include/wx/msw/wrapwin.h )
	SOURCE_GROUP( "MSW Headers" FILES ${BASE_MSW_HDRS} )
ENDIF( WIN32 )

